name: CodeDeploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip application files
        run: |
          zip -r app-v1.zip index.html appspec.yml scripts/

      - name: Upload to S3
        run: |
          aws s3 cp app-v1.zip s3://mg-codedeploy-revisions/app-v1.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name mg-app-deploy \
            --deployment-group-name mg-deploy-group \
            --s3-location bucket=mg-codedeploy-revisions,key=app-v1.zip,bundleType=zip \
            --region us-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

